language: android
jdk: oraclejdk8
dist: trusty

env:
  global:

android:
  components:

  licenses:
  
before_install:
  - - chmod +x gradlew
  - yes | sdkmanager "platforms;android-29"
before_script:
